# Generated by Django 5.2.8 on 2025-11-28 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientside', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='number',
            name='collection_day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10),
        ),
    ]
